document.addEventListener("DOMContentLoaded",()=>{
const $=id=>document.getElementById(id);
const modeManualBtn=$("modeManualBtn"),modeBatchBtn=$("modeBatchBtn"),manualSection=$("manualSection"),batchSection=$("batchSection");
const docTypeSelect=$("docType"),inputName=$("inputName"),inputFather=$("inputFather"),inputDob=$("inputDob"),inputGender=$("inputGender"),inputNumber=$("inputNumber"),inputAddress=$("inputAddress"),photoInput=$("photoInput");
const generateBtn=$("generateBtn"),randomizeBtn=$("randomizeBtn"),clearBtn=$("clearBtn"),downloadCardBtn=$("downloadCardBtn"),canvas=$("cardCanvas"),emptyPreview=$("emptyPreview"),manualStatus=$("manualStatus");
const uploadExcelTrigger=$("uploadExcelTrigger"),excelUpload=$("excelUpload"),excelFileName=$("excelFileName"),downloadTemplateBtn=$("downloadTemplateBtn"),bulkPhotoUpload=$("bulkPhotoUpload"),bulkZipUpload=$("bulkZipUpload"),clearPhotosBtn=$("clearPhotosBtn"),photoUploadStatus=$("photoUploadStatus");
const batchStatus=$("batchStatus"),recordCount=$("recordCount"),matchedCount=$("matchedCount"),missingCount=$("missingCount"),batchTableBody=$("batchTableBody"),downloadAllPan=$("downloadAllPan"),downloadAllAadhaar=$("downloadAllAadhaar"),downloadBothZip=$("downloadBothZip");
let currentPhotoDataUrl=null,hasGeneratedManual=false,parsedRecords=[];let bulkPhotos={};
if(window.BULK_PHOTOS&&typeof window.BULK_PHOTOS==="object")bulkPhotos={...window.BULK_PHOTOS};
const normalizeFileName=v=>String(v||"").trim().replace(/\\/g,"/").split("/").pop().toLowerCase();
function findBulkPhoto(photoValue,name){const requested=normalizeFileName(photoValue);const keys=Object.keys(bulkPhotos);if(requested){const k=keys.find(x=>normalizeFileName(x)===requested);if(k)return{dataUrl:bulkPhotos[k],filename:k,reason:"Matched Photo column"};}const normalizedName=String(name||"").toLowerCase().replace(/\.[^/.]+$/,"" ).replace(/[^a-z0-9]/g,"");if(normalizedName){const k=keys.find(x=>String(x).toLowerCase().replace(/\.[^/.]+$/,"" ).replace(/[^a-z0-9]/g,"")===normalizedName);if(k)return{dataUrl:bulkPhotos[k],filename:k,reason:"Matched person name"};}return{dataUrl:null,filename:requested,reason:requested?"Photo not found":"No photo specified"};}
function setMode(batch){manualSection.style.display=batch?"none":"block";batchSection.style.display=batch?"block":"none";modeBatchBtn.classList.toggle("secondary",!batch);modeManualBtn.classList.toggle("secondary",batch);}
modeManualBtn.onclick=()=>setMode(false);modeBatchBtn.onclick=()=>setMode(true);
photoInput.onchange=e=>{const f=e.target.files[0];if(!f){currentPhotoDataUrl=null;return;}const r=new FileReader();r.onload=ev=>{currentPhotoDataUrl=ev.target.result;if(hasGeneratedManual)renderManual();};r.readAsDataURL(f);};
function manualPerson(){const type=docTypeSelect.value;const number=inputNumber.value.trim();return{name:inputName.value.trim(),parentName:inputFather.value.trim(),dob:inputDob.value.trim(),gender:inputGender.value,pan:type==="PAN"?(number||generatePANNumber()):"",aadhaar:type==="Aadhaar"?(number||generateAadharNumber()):"",address:inputAddress.value.trim()};}
async function renderManual(){const person=manualPerson();if(!person.name&&!person.parentName&&!person.dob&&!person.address&&!inputNumber.value&&!currentPhotoDataUrl){canvas.getContext("2d").clearRect(0,0,canvas.width,canvas.height);emptyPreview.style.display="block";downloadCardBtn.disabled=true;return;}emptyPreview.style.display="none";await drawSyntheticDocument(canvas,person,docTypeSelect.value,currentPhotoDataUrl);downloadCardBtn.disabled=false;}
generateBtn.onclick=async()=>{if(!inputName.value.trim()){manualStatus.textContent="Enter at least a name before generating.";return;}hasGeneratedManual=true;await renderManual();manualStatus.textContent="Synthetic test document generated.";};
randomizeBtn.onclick=async()=>{inputName.value=generateRandomName();inputFather.value=generateRandomFatherName();inputDob.value=generateRandomDOB();inputGender.value=generateRandomGender();inputNumber.value="";inputAddress.value=generateRandomAddress();hasGeneratedManual=true;await renderManual();manualStatus.textContent="Random synthetic test data generated.";};
clearBtn.onclick=()=>{inputName.value="";inputFather.value="";inputDob.value="";inputGender.value="";inputNumber.value="";inputAddress.value="";photoInput.value="";currentPhotoDataUrl=null;hasGeneratedManual=false;manualStatus.textContent="";canvas.getContext("2d").clearRect(0,0,canvas.width,canvas.height);emptyPreview.style.display="block";downloadCardBtn.disabled=true;};
[docTypeSelect,inputName,inputFather,inputDob,inputGender,inputNumber,inputAddress].forEach(el=>el.addEventListener("input",()=>{if(hasGeneratedManual)renderManual();}));
downloadCardBtn.onclick=()=>{if(canvas.width&&canvas.height){const a=document.createElement("a");a.href=canvas.toDataURL("image/jpeg",.92);a.download=`synthetic_${docTypeSelect.value}_${Date.now()}.jpg`;a.click();}};

function registerPhoto(fileName,dataUrl){bulkPhotos[fileName]=dataUrl;}
async function readImageFile(file){return new Promise((resolve,reject)=>{const r=new FileReader();r.onload=e=>resolve(e.target.result);r.onerror=reject;r.readAsDataURL(file);});}
async function loadPhotoFiles(files){let count=0;for(const f of Array.from(files||[])){if(!f.type.startsWith("image/"))continue;registerPhoto(f.name,await readImageFile(f));count++;}photoUploadStatus.textContent=`${count} image(s) added. ${Object.keys(bulkPhotos).length} total available.`;}
bulkPhotoUpload.onchange=async e=>{await loadPhotoFiles(e.target.files);if(parsedRecords.length)relinkPhotos();};
bulkZipUpload.onchange=async e=>{const file=e.target.files[0];if(!file)return;try{const zip=await JSZip.loadAsync(file);let count=0;for(const [name,entry] of Object.entries(zip.files)){if(entry.dir||!(/\.(jpe?g|png|webp|gif)$/i.test(name)))continue;const blob=await entry.async("blob");const dataUrl=await readImageFile(new File([blob],name,{type:blob.type||"image/jpeg"}));registerPhoto(name.split("/").pop(),dataUrl);count++;}photoUploadStatus.textContent=`${count} image(s) extracted. ${Object.keys(bulkPhotos).length} total available.`;if(parsedRecords.length)relinkPhotos();}catch(err){photoUploadStatus.textContent="Could not read the ZIP file.";console.error(err);}};
clearPhotosBtn.onclick=()=>{bulkPhotos={};if(window.BULK_PHOTOS)bulkPhotos={...window.BULK_PHOTOS};bulkPhotoUpload.value="";bulkZipUpload.value="";photoUploadStatus.textContent="Uploaded photos cleared.";if(parsedRecords.length)relinkPhotos();};
function relinkPhotos(){parsedRecords.forEach(r=>{const m=findBulkPhoto(r.photo,r.name);r.photoDataUrl=m.dataUrl;r.photoFilename=m.filename;r.photoMatchReason=m.reason;});renderBatchTable();updateSummary();}

uploadExcelTrigger.onclick=()=>excelUpload.click();
function valueFromRow(row,keys){for(const k of keys){if(row[k]!==undefined&&String(row[k]).trim()!=="")return row[k];}return "";}
downloadTemplateBtn.onclick=e=>{e.preventDefault();const data=[["Name","DOB","Gender","Address","ParentName","Photo","PAN","Aadhaar"],["TEST PERSON ONE","15/06/1995","Male","12 Park Street, Mumbai, Maharashtra - 400001","TEST PARENT ONE","person1.jpg","",""],["TEST PERSON TWO","22/11/1998","Female","45 MG Road, Bengaluru, Karnataka - 560001","TEST PARENT TWO","person2.jpg","",""],["TEST PERSON THREE","10/04/1997","Male","78 Main Road, Pune, Maharashtra - 411001","TEST PARENT THREE","person3.jpg","","1234 5678 9012"]];const wb=XLSX.utils.book_new(),ws=XLSX.utils.aoa_to_sheet(data);ws["!cols"]=[{wch:22},{wch:14},{wch:12},{wch:52},{wch:24},{wch:22},{wch:16},{wch:18}];XLSX.utils.book_append_sheet(wb,ws,"Template");XLSX.writeFile(wb,"ocr-test-data-template.xlsx");};
excelUpload.onchange=e=>{const file=e.target.files[0];if(!file)return;excelFileName.textContent=file.name;batchStatus.textContent="Reading Excel...";const r=new FileReader();r.onload=ev=>{try{const wb=XLSX.read(new Uint8Array(ev.target.result),{type:"array"});const ws=wb.Sheets[wb.SheetNames[0]];const rows=XLSX.utils.sheet_to_json(ws,{defval:""});if(!rows.length){batchStatus.textContent="Excel file is empty.";return;}parsedRecords=rows.map((row,index)=>{const name=String(valueFromRow(row,["Name","NAME","name"])||generateRandomName()).trim().toUpperCase();const photo=String(valueFromRow(row,["Photo","PHOTO","photo"])).trim();const m=findBulkPhoto(photo,name);const panInput=String(valueFromRow(row,["PAN","Pan","pan"])).trim();const aadhaarInput=String(valueFromRow(row,["Aadhaar","AADHAAR","Aadhar","AADHAR","aadhaar"])).trim();return{rowNumber:index+2,name,dob:normalizeDate(valueFromRow(row,["DOB","dob"])||generateRandomDOB()),gender:String(valueFromRow(row,["Gender","GENDER","gender"])||generateRandomGender()).trim(),address:String(valueFromRow(row,["Address","ADDRESS","address"])||generateRandomAddress()).trim(),parentName:String(valueFromRow(row,["ParentName","PARENTNAME","FatherName","Father's Name"])||generateRandomFatherName()).trim().toUpperCase(),photo,photoDataUrl:m.dataUrl,photoFilename:m.filename,photoMatchReason:m.reason,pan:panInput||generatePANNumber(),aadhaar:aadhaarInput||generateAadharNumber()};});renderBatchTable();updateSummary();batchStatus.textContent=`Parsed ${parsedRecords.length} record(s).`;setBatchButtons();}catch(err){console.error(err);batchStatus.textContent="Could not parse Excel. Check the headers and file format.";}};r.readAsArrayBuffer(file);};
function updateSummary(){recordCount.textContent=parsedRecords.length;const matched=parsedRecords.filter(r=>!!r.photoDataUrl).length;matchedCount.textContent=matched;missingCount.textContent=parsedRecords.length-matched;}
function setBatchButtons(){const disabled=parsedRecords.length===0;downloadAllPan.disabled=disabled;downloadAllAadhaar.disabled=disabled;downloadBothZip.disabled=disabled;}
function escapeHtml(v){return String(v??"").replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;").replace(/'/g,"&#039;");}
function renderBatchTable(){recordCount.textContent=parsedRecords.length;if(!parsedRecords.length){batchTableBody.innerHTML='<tr><td colspan="8" class="empty-cell">No Excel file uploaded yet.</td></tr>';return;}batchTableBody.innerHTML=parsedRecords.map((r,i)=>{const photo=r.photoDataUrl?`<div class="photo-cell"><img class="batch-photo" src="${r.photoDataUrl}" alt=""><small>${escapeHtml(r.photoFilename||r.photo)}</small><span class="table-status-ok">✓ matched</span></div>`:`<div class="photo-cell"><div class="photo-missing">Missing</div><small>${escapeHtml(r.photo||"Not specified")}</small><span class="table-status-missing">✗ missing</span></div>`;return `<tr><td>${i+1}</td><td>${photo}</td><td>${escapeHtml(r.name)}</td><td>${escapeHtml(r.dob)}</td><td>${escapeHtml(r.gender)}</td><td><code>${escapeHtml(r.pan)}</code></td><td><code>${escapeHtml(r.aadhaar)}</code></td><td>${escapeHtml(r.address)}</td></tr>`;}).join("");}
async function generateZipArchive(type){if(!parsedRecords.length){batchStatus.textContent="No records available.";return;}const zip=new JSZip(),folder=zip.folder(type==="PAN"?"PAN_Cards":"Aadhaar_Cards"),temp=document.createElement("canvas");for(let i=0;i<parsedRecords.length;i++){const r=parsedRecords[i];try{await drawSyntheticDocument(temp,r,type,r.photoDataUrl);const base64=temp.toDataURL("image/jpeg",.92).split(",")[1];const safe=r.name.replace(/\s+/g,"_").replace(/[^a-zA-Z0-9_-]/g,"")||`record_${i+1}`;folder.file(`${i+1}_${safe}_${type}.jpg`,base64,{base64:true});}catch(err){console.error(err);}}batchStatus.textContent=`Preparing ${type} ZIP...`;const blob=await zip.generateAsync({type:"blob"});downloadBlob(blob,`${type}_Test_Cards.zip`);batchStatus.textContent=`${type} ZIP ready.`;}
function downloadBlob(blob,name){const url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);}
downloadAllPan.onclick=()=>generateZipArchive("PAN");downloadAllAadhaar.onclick=()=>generateZipArchive("Aadhaar");downloadBothZip.onclick=async()=>{if(!parsedRecords.length)return;const zip=new JSZip(),pan=zip.folder("PAN_Cards"),aad=zip.folder("Aadhaar_Cards"),temp=document.createElement("canvas");for(let i=0;i<parsedRecords.length;i++){const r=parsedRecords[i],safe=r.name.replace(/\s+/g,"_").replace(/[^a-zA-Z0-9_-]/g,"")||`record_${i+1}`;await drawSyntheticDocument(temp,r,"PAN",r.photoDataUrl);pan.file(`${i+1}_${safe}_PAN.jpg`,temp.toDataURL("image/jpeg",.92).split(",")[1],{base64:true});await drawSyntheticDocument(temp,r,"Aadhaar",r.photoDataUrl);aad.file(`${i+1}_${safe}_Aadhaar.jpg`,temp.toDataURL("image/jpeg",.92).split(",")[1],{base64:true});}const blob=await zip.generateAsync({type:"blob"});downloadBlob(blob,"All_Synthetic_Test_Cards.zip");batchStatus.textContent="Combined ZIP ready.";};
setMode(false);setBatchButtons();updateSummary();
});
